In [1]:
import re
import matplotlib.pyplot as plt
import string
from nltk.corpus import stopwords
import nltk
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize.treebank import TreebankWordDetokenizer
from collections import Counter
from wordcloud import WordCloud
from nltk.corpus import stopwords
import nltk
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords
import gensim
from sklearn.model_selection import train_test_split
import spacy
import pickle
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt 
import tensorflow as tf
import keras
import numpy as np
import pandas as pd
print('Done')

Done


In [2]:
train = pd.read_csv("/content/drive/MyDrive/DeepLearningProject/train.csv")

In [3]:
train.dropna(subset = ["text"], inplace=True)

In [4]:
train.head(15)

textID  ... sentiment
0   cb774db0d1  ...   neutral
1   549e992a42  ...  negative
2   088c60f138  ...  negative
3   9642c003ef  ...  negative
4   358bd9e861  ...  negative
5   28b57f3990  ...   neutral
6   6e0c6d75b1  ...  positive
7   50e14c0bb8  ...   neutral
8   e050245fbd  ...   neutral
9   fc2cbefa9d  ...  positive
10  2339a9b08b  ...   neutral
11  16fab9f95b  ...  positive
12  74a76f6e0a  ...  negative
13  04dd1d2e34  ...  negative
14  bbe3cbf620  ...   neutral

[15 rows x 4 columns]

In [5]:
#Let's get the dataset lenght
len(train)

27480

In [6]:
#Is there any other different value than neutral, negative and positive?
train['sentiment'].unique()

array(['neutral', 'negative', 'positive'], dtype=object)

In [7]:
#How's distributed the dataset? Is it biased?
train.groupby('sentiment').nunique()

textID   text  selected_text
sentiment                              
negative     7781   7781           5861
neutral     11117  11117          11111
positive     8582   8582           5537

In [8]:
#Let's keep only the columns that we're going to use
train = train[['text','sentiment']]
train.head()

text sentiment
0                I`d have responded, if I were going   neutral
1      Sooo SAD I will miss you here in San Diego!!!  negative
2                          my boss is bullying me...  negative
3                     what interview! leave me alone  negative
4   Sons of ****, why couldn`t they put them on t...  negative

In [9]:

#Is there any null value?
train["text"].isnull().sum()

0

In [10]:
def depure_data(data):
    
    #Removing URLs with a regular expression
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    data = url_pattern.sub(r'', data)

    # Remove Emails
    data = re.sub('\S*@\S*\s?', '', data)

    # Remove new line characters
    data = re.sub('\s+', ' ', data)

    # Remove distracting single quotes
    data = re.sub("\'", "", data)
        
    return data

In [11]:
def sent_to_words(sentences):
    for sentence in sentences:
        yield(gensim.utils.simple_preprocess(str(sentence),     deacc=True))

In [12]:
def detokenize(text):
    return TreebankWordDetokenizer().detokenize(text)

In [13]:
temp = []
#Splitting pd.Series to list
data_to_list = train['text'].values.tolist()
for i in range(len(data_to_list)):
    temp.append(depure_data(data_to_list[i]))
list(temp[:5])

[' I`d have responded, if I were going',
 ' Sooo SAD I will miss you here in San Diego!!!',
 'my boss is bullying me...',
 ' what interview! leave me alone',
 ' Sons of ****, why couldn`t they put them on the releases we already bought']

In [14]:
def sent_to_words(sentences):
    for sentence in sentences:
        yield(gensim.utils.simple_preprocess(str(sentence), deacc=True))  # deacc=True removes punctuations
        

data_words = list(sent_to_words(temp))

print(data_words[:10])

[['have', 'responded', 'if', 'were', 'going'], ['sooo', 'sad', 'will', 'miss', 'you', 'here', 'in', 'san', 'diego'], ['my', 'boss', 'is', 'bullying', 'me'], ['what', 'interview', 'leave', 'me', 'alone'], ['sons', 'of', 'why', 'couldn', 'they', 'put', 'them', 'on', 'the', 'releases', 'we', 'already', 'bought'], ['some', 'shameless', 'plugging', 'for', 'the', 'best', 'rangers', 'forum', 'on', 'earth'], ['am', 'feedings', 'for', 'the', 'baby', 'are', 'fun', 'when', 'he', 'is', 'all', 'smiles', 'and', 'coos'], ['soooo', 'high'], ['both', 'of', 'you'], ['journey', 'wow', 'just', 'became', 'cooler', 'hehe', 'is', 'that', 'possible']]


In [15]:
len(data_words)

27480

In [16]:
data = []
for i in range(len(data_words)):
    data.append(detokenize(data_words[i]))
print(data[:5])

['have responded if were going', 'sooo sad will miss you here in san diego', 'my boss is bullying me', 'what interview leave me alone', 'sons of why couldn they put them on the releases we already bought']


In [17]:
data = np.array(data)

In [18]:
labels = np.array(train['sentiment'])
y = []
for i in range(len(labels)):
    if labels[i] == 'neutral':
        y.append(0)
    if labels[i] == 'negative':
        y.append(1)
    if labels[i] == 'positive':
        y.append(2)
y = np.array(y)
labels = tf.keras.utils.to_categorical(y, 3, dtype="float32")
del y

In [19]:
len(labels)

27480

## Data sequencing and splitting
### We'll implement the Keras tokenizer as well as its pad_sequences method to transform our text data into 3D float data, otherwise our neural networks won't be able to be trained on it.

In [20]:

from keras.models import Sequential
from keras import layers
from keras.optimizers import RMSprop,Adam
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras import regularizers
from keras import backend as K
from keras.callbacks import ModelCheckpoint
max_words = 5000
max_len = 200

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(data)
sequences = tokenizer.texts_to_sequences(data)
tweets = pad_sequences(sequences, maxlen=max_len)
print(tweets)

[[   0    0    0 ...   65  139   42]
 [   0    0    0 ...    8 1400 2205]
 [   0    0    0 ... 1301    7   13]
 ...
 [   0    0    0 ...  624  837 2731]
 [   0    0    0 ...   23  663    4]
 [   0    0    0 ... 2206  218  634]]


In [21]:
print(labels)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [22]:

#Splitting the data
X_train, X_test, y_train, y_test = train_test_split(tweets,labels, random_state=0)
print (len(X_train),len(X_test),len(y_train),len(y_test))

20610 6870 20610 6870


## Model building
SimpleRNN model

In [ ]:
model0 = Sequential()
model0.add(layers.Embedding(max_words, 64))
model0.add(layers.GRU(64))
model0.add(layers.Dense(3,activation='softmax'))

print(model0.summary())

model0.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
checkpoint0 = ModelCheckpoint("/content/drive/MyDrive/DeepLearningProject/TweetSentimentAnalysis/GRU/full_text_GRU_model0.hdf5", monitor='val_accuracy', verbose=1,save_best_only=True, mode='auto', period=1,save_weights_only=False)
history = model0.fit(X_train, y_train, epochs=20,validation_data=(X_test, y_test),callbacks=[checkpoint0])

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          320000    
_________________________________________________________________
gru (GRU)                    (None, 64)                24960     
_________________________________________________________________
dense (Dense)                (None, 3)                 195       
Total params: 345,155
Trainable params: 345,155
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/20
645/645 [==============================] - 62s 92ms/step - loss: 0.9669 - accuracy: 0.5262 - val_loss: 0.7368 - val_accuracy: 0.6881

Epoch 00001: val_accuracy improved from -inf to 0.68806, saving model to /content/drive/MyDrive/DeepLearningProject/TweetSentimentAnalysis/GRU/full_text_GRU_model0.hdf5
Epoch 2/20
645/645 [==============================] - 63s 98m

In [ ]:
test_loss, test_acc = model0.evaluate(X_test, y_test, verbose=2)
print('Model accuracy: ',test_acc)

In [ ]:
predictions = model0.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test.argmax(axis=1), np.around(predictions, decimals=0).argmax(axis=1))

In [ ]:
import seaborn as sns
conf_matrix = pd.DataFrame(matrix, index = ['Neutral','Negative','Positive'],columns = ['Neutral','Negative','Positive'])
#Normalizing
conf_matrix = conf_matrix.astype('float') / conf_matrix.sum(axis=1)[:, np.newaxis]
plt.figure(figsize = (15,15))
sns.heatmap(conf_matrix, annot=True, annot_kws={"size": 15})

In [ ]:
sentiment = ['Neutral','Negative','Positive']

In [ ]:
sequence = tokenizer.texts_to_sequences(['this experience has been the worst , want my money back'])
test = pad_sequences(sequence, maxlen=max_len)
sentiment[np.around(model0.predict(test), decimals=0).argmax(axis=1)[0]]

In [ ]:
sequence = tokenizer.texts_to_sequences(['this deep learning project is the best ever'])
test = pad_sequences(sequence, maxlen=max_len)
sentiment[np.around(model0.predict(test), decimals=0).argmax(axis=1)[0]]

In [ ]:
sequence = tokenizer.texts_to_sequences(['i hate youtube ads, they are annoying'])
test = pad_sequences(sequence, maxlen=max_len)
sentiment[np.around(model0.predict(test), decimals=0).argmax(axis=1)[0]]

In [ ]:
sequence = tokenizer.texts_to_sequences(['i really loved how the technician helped me with the issue that i had'])
test = pad_sequences(sequence, maxlen=max_len)
sentiment[np.around(model0.predict(test), decimals=0).argmax(axis=1)[0]]